#!/bin/bash

# Check whether yt-dlp is installed or not. Install if required.
pacman -Q | grep yt-dlp || sudo pacman -Syu --noconfirm yt-dlp

cat << EOF
Please Select:

    1. Download Single YouTube Video
    2. Download Single YouTube Audio
    3. Download YouTube Video Playlist
    4. Download YouTube Audio Playlist
    5. Quit

EOF
echo -n "Enter one at a time [1-5]: "
read -r sel path

case $sel in
    1) mkdir -pv $HOME/Videos/ez-video/ && cd $HOME/Videos/ez-video/ && read -p "Enter URL here: " URL && yt-dlp -o "%(title)s.%(ext)s" $URL && cd - ;;
    2) mkdir -pv $HOME/Music/ez-audio/ && cd $HOME/Music/ez-audio/ && read -p "Enter URL here: " URL && yt-dlp --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" $URL && cd - ;;
    3) mkdir -pv $HOME/Videos/ez-playlist/ && cd $HOME/Videos/ez-playlist/ && read -p "Enter URL here: " URL && yt-dlp --yes-playlist -o "%(title)s.%(ext)s" $URL && cd - ;;
    4) mkdir -pv $HOME/Music/ez-playlist/ && cd $HOME/Music/ez-playlist/ && read -p "Enter URL here: " URL && yt-dlp --yes-playlist --extract-audio --audio-format mp3 -o "%(title)s.%(ext)s" $URL && cd - ;;
    5) echo "Quiting now.." ;;
    *) echo "Invalid input. Exiting.." >&2
       exit 1
esac
