#!/bin/bash

# Check whether yt-dlp is installed or not. Install if required.
pacman -Q | grep yt-dlp || sudo pacman -Syu --noconfirm yt-dlp

# Main menu offering download options
while true; do
    cat <<EOF
Please choose Media Download Option:

      v - Download Single Video
      vp - Download Video Playlist
      a - Download Single Audio
      ap - Download Audio Playlist
      q - Quit
EOF

    read -p "Enter your choice (v, vp, a, ap, q): " option

    case $option in
        v)
            dir="$HOME/Videos"
            ext=".mp4"
            yt_options="-f bestvideo+bestaudio"
            ;;
        vp)
            dir="$HOME/Videos"
            ext=".mp4"
            yt_options="-f bestvideo+bestaudio --yes-playlist"
            ;;
        a)
            dir="$HOME/Music"
            ext=".mp3"
            yt_options="--extract-audio --audio-format mp3 --audio-quality 0"
            ;;
        ap)
            dir="$HOME/Music"
            ext=".mp3"
            yt_options="--yes-playlist --extract-audio --audio-format mp3 --audio-quality 0"
            ;;
        q)
            echo "Quitting..."
            exit 0
            ;;
        *)
            echo "Invalid input. Please try again."
            ;;
    esac

    # Download media
    read -p "Enter the YouTube/Facebook/Odysee URL: " url

    # Save directory with optional user input
    read -p "Enter Save directory ($dir): " save_dir
    save_dir=${save_dir:-"$dir"}

    # Download media with yt-dlp
    mkdir -p "$save_dir"
    yt-dlp $yt_options -o "$save_dir/%(title)s$ext" "$url"
    if [[ $? -eq 0 ]]; then
        echo "Download successful! File saved to $save_dir"
    else
        echo "Download failed. Please check your URL and try again."
    fi
done
